### ISSUE TITLE
CORS ROM Issue

### ISSUE THREAD

**Issue by Pelican104** [pdjstone/archimedes-live#21]
Trying to set up a local version of Archimedes-Live. Got as far as Make Serve and all seems good but although the interface appears the emulator never starts, it seems it is hard coded to pull roms from your server and cant get them due to CORS restrictions. Can the ROMS not be stored on the local server?

![image](https://user-images.githubusercontent.com/42071538/218287040-3d4e673f-7063-4c85-9581-dd65cb336215.png)

**Comment by pdjstone** [comment]
Thanks for testing out the code! 

I see you're serving it from 192.168.0.x, which is causing the CORS issue. Currently the JS will fetch the ROMs from a local path only if running on localhost. I should really have a build option to configure that. For now you can edit the code at the top of machine-config.js and software-browser.js to tell it where to fetch files from.

**Comment by Pelican104** [comment]
Awesome that works perfectly. just changed the reference to 'localhost' a few lines down to the   local server IP address '192.168.0.xxx' in both files and all works great

**Comment by pdjstone** [comment]
I've reversed the logic in a9bb45a to only load resources from files-archi.medes.live if the code is running on archi.medes.live, so this shouldn't trip anyone up in future.
